### ISSUE TITLE
Profile-Guided Optimization? (feature suggestion)

### ISSUE THREAD

**Issue by noahgibbs** [vnmakarov/ruby#6]
Apparently profile-guided optimization of the Ruby interpreter gives good results when applied to OptCarrot, close to a 30% speedup. Not sure if this is interesting to you, but I could imagine that working very well with MJIT...

https://gist.github.com/jamatthews/f993e18b6c79415fd939779a045772e0

**Comment by vnmakarov** [comment]
On 12/04/2017 02:25 PM, Noah Gibbs wrote:
>
> Apparently profile-guided optimization of the Ruby interpreter gives 
> good results when applied to OptCarrot, close to a 30% speedup. Not 
> sure if this is interesting to you, but I could imagine that working 
> very well with MJIT...
>
> https://gist.github.com/jamatthews/f993e18b6c79415fd939779a045772e0
>
>
   Yes, it is really nice improvement.

   I would not say that it is PGO.  It is a link time optimizations 
guided by profile information.  Usually PGO only gives 7% on SpecCPU.  
LTO permits inlining and interprocedural optimizations between different 
files.  If it not guided, its effect is pretty small.

   Although PGO is old, it is not popular because it complicates a build 
procedure considerably.  The effect can be opposite if the actual 
profile is quite different from one used during building. But for 
interpreters it can work because there are a lot of code always hot 
independently from interpreted program.

   LTO is pretty new and there are still cases where it is not 
reliable.  Also some programs can not be compiled with LTO because of a 
bit different definitions of the same in different files.

As for MJIT, I thought about this too.  Inlining in MJIT should be 
profile guided.  As for usage of other profile info (it is mostly basic 
block frequency execution), it is doable to implement in MJIT too 
although it is more complicated than using call frequency for inlining.  
So plans to use BB frequency are very far away for me.

**Comment by noahgibbs** [comment]
Thank makes sense. Thank you!
